### ISSUE TITLE
having prouble to get the AmbienceHue script running

### ISSUE THREAD

**Issue by jarvis121** [G2Jose/AmbienceHue#1]
This is what i get when i type in the commands as they are in the readme. 

Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/lx/z3ptk2453z1dgfqnnb_b8m2r0000gn/T/pip-build-03sOO0/pyobjc-framework-QTKit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/lx/z3ptk2453z1dgfqnnb_b8m2r0000gn/T/pip-1_mtqM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/lx/z3ptk2453z1dgfqnnb_b8m2r0000gn/T/pip-build-03sOO0/pyobjc-framework-QTKit/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by G2Jose** [comment]
That's strange. Do you have the homebrew version of python set up? Can you also try upgrading pip using the command shown `pip install --upgrade pip` (You may need to run as `sudo`) depending on your setup.

**Comment by jarvis121** [comment]
i did the python upgrade. But i couldn't run it as sudo though. Is there a way to actually do that?

**Comment by jarvis121** [comment]
Hey, I tried the pip upgrade as sudo again. This what I got

Jarvis-MBP:~ JARVIS$ sudo pip install --upgrade pip
Password:
The directory '/Users/JARVIS/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/JARVIS/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages
Jarvis-MBP:~ JARVIS$

**Comment by G2Jose** [comment]
Hi @jarvis121, what version of MacOS / OSX are you running? I just found out that this will not run on Sierra, as Apple has removed `QTKit/QTKit.h` from the latest Apple Developer tools (looking online I was able to find a few other projects that were affected by it https://github.com/opencv/opencv/issues/6913). I am yet to look into an alternative to QTKit.h.

**Comment by jarvis121** [comment]
Hey, thanks for still focusing that problem. 

It's true, I am trying to run it under Sierra. 

Keep me up to date, when there is anything I can do to get it running.

**Comment by G2Jose** [comment]
@jarvis121, I recently upgraded this script to work on Sierra! Do feel free to give it a try and post back if you run into any issues.
